mass: 11.5 # as stated in https://flex.flinders.edu.au/file/27aa0064-9de2-441c-8a17-655405d5fc2e/1/ThesisWu2018.pdf
model: bluerov2
inertial:
  ixx: 0.16
  iyy: 0.16
  izz: 0.16
  ixy: 0
  ixz: 0
  iyz: 0
cog: [0, 0, 0.02]
# CoB represented wrt ENU convention
cob: [0, 0, 0]
volume: 1.83826
length: 2.6
height: 1.6
width: 1.5
base_link: base_link
Ma: # added mass? not sure about this one
- [1.7182, 0, 0, 0, 0, 0]
- [0, 0, 0, 0, 0, 0]
- [0, 0, 5.468, 0, 0, 0]
- [0, 0, 0, 0, 0, 0]
- [0, 0, 0, 0, 1.2481, 0]
- [0, 0, 0, 0, 0, 0.4006]
# In the model, the damping coefficients are pre-multiplied by -1
linear_damping: [-4.03, -6.22, -5.18, -0.07, -0.07, -0.07]
quad_damping: [-18.18, -21.66, -36.99, -1.55, -1.55, -1.55] 
density: 1028.0
