inertial_frame_id: world
waypoints:
  -
    point: [0, 2, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [16, 12, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 12, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 16, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [25, 20, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [30, 40, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [36, 45, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [60, 70, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [105, 56, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -20, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -20, -8]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
