velocity_control/linear_d: 1.0 # as seen in https://projekter.aau.dk/projekter/files/387609647/MPC_control_for_the_BlueROV2_Theory_and_Implementation.pdf
velocity_control/linear_i: 0.02
velocity_control/linear_p: 0.5
velocity_control/linear_sat: 1.0

velocity_control/angular_d: 0.03
velocity_control/angular_i: 0.001
velocity_control/angular_p: 0.09
velocity_control/angular_sat: 2.0