sudo: required
dist: trusty
language: generic
compiler:
  - gcc
cache:
  directories:
    - $HOME/.ccache  # can be any valid cache location
env:
  global:
    - LIBGL_ALWAYS_SOFTWARE=1
    - VERBOSE_OUTPUT='false'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
    - CCACHE_DIR=$HOME/.ccache
    - CATKIN_LINT=true
    - CATKIN_LINT_ARGS="--ignore link_directory"
matrix:
  include:
    - env: PRERELEASE=true ROS_DISTRO=kinetic 
    - env: ROS_DISTRO=kinetic 
    - env: PRERELEASE=true ROS_DISTRO=melodic
    - env: ROS_DISTRO=melodic
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config -b master
script:
  - source .ci_config/travis.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8c9c6426a721fbb8341
    on_success: change
    on_failure: always
    on_start: never
  slack: uuvsimulator:CeZErwayGqGpYxJaLzCEbjip
